services:
  # web:
  #   build:
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "8000:5000"
  #   volumes:
  #     - .:/code
  #   environment:
  #     FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"